name: ???
scenario: ???
dataset: ???

tensor_type: "torch"
device: "gpu"
num_workers: 4
downscale_method: 'interp:linear'

start_date:  "10/02/2012"
days_per_batch: 16
hours_per_step: 1

nbatches: 50
batch_iter: 20
nepochs: 100
lr: 1e-4

origin: (0,0)
tile_size: 16

coords: { 'x': 'XC', 'y': 'YC' }
input_variables: { 'sst': sea_surface_temperature, 'sss': sea_surface_salinity, 'ssh': sea_surface_humidity }
target_variables: [ 'sst' ]



