name: ???
scenario: ???
dataset: ???

tensor_type: "torch"
device: "gpu"
num_workers: 4
downscale_method: 'interp:linear'
training_version: '{name}-{dataset}.{scenario}'

start_date:  "9/13/2011"
days_per_batch: 4
hours_per_step: 4

nbatches: 2
batch_iter: 1
nepochs: 1
lr: 1e-3

origin: { x: 0, y: 0 }
tile_size: { x: 16, y: 16 }
tile_grid: { x: 4, y: 4 }
conform_to_grid: false

coords: { 'x': 'XC', 'y': 'YC', z: '' }
input_variables: { 'sst': sea_surface_temperature }
target_variables: [ 'sst' ]
forcing_variables: []



