name: ???
scenario: ???
dataset: ???

dataset_version: 'merra2.sr.1'
params: "small"
nc_format: 'sres'
tensor_type: "torch"
device: "gpu"
num_workers: 4
downscale_method: 'interp:linear'

start_date:  "10/02/2012"
days_per_batch: 16
hours_per_step: 6

nbatches: 50
batch_iter: 20
nepochs: 100
lr: 1e-4

train_steps: [0]
nsteps_input: 1

weight_decay: 0.0
error_threshold: 1.0

origin: { x: -120, y: -60 }
tile_size: { x: 16, y: 16 }
tile_grid: { x: 4, y: 4 }
levels:  [850, 1000]
conform_to_grid: true

coords: { x: "lon", y: "lat", z: "level", t: "time" }
statnames: { mean: "mean_by_level", std: "stddev_by_level", mean_diff: "diffs_mean_by_level", std_diff: "diffs_stddev_by_level" }

input_variables: { 2m_temperature: 'T2M' }
target_variables: [ '2m_temperature' ]
forcing_variables: [  ]
constants: [  ]
feature_list: [ '2m_temperature' ]


