name: ???
scenario: ???
dataset: ???
training_version: ???

tensor_type: "torch"
device: "gpu"
num_workers: 4

batch_size: { train: 50, valid: 50, test: 37 }
nepochs: 30
lr: 1e-4

origin: { train: { x: 0, y: 0 }, valid: { x: 0, y: 0 }, test: { x: 0, y: 0 } }
tile_grid: { train: { x: -1, y: -1 }, valid: { x: -1, y: -1 }, test: { x: -1, y: -1 } }
tile_size: { x: 48, y: 48 }
batch_domain:  'tiles'
conform_to_grid: false
upsample_mode: bicubic
downsample_mode: bicubic

input_variables: { SST: sea_surface_temperature }
variable_ranges: { SST: { min: 3.0, max: 24.0 } }
target_variables: [ SST ]
forcing_variables: []





