root:      "/explore/nobackup/projects/ilab/data/SR"
results:   "{root}/results"
cache:     "{root}/cache"
processed: '{root}/processed'

dataset_root:  "/explore/nobackup/people/jli30/share/data/"
dataset_files: { lr: "{varname}_192x192/{tset}/{res}_{varname}/X{usf}/{res}_{varname}_{index}.npy",
                 hr: "{varname}_192x192/{tset}/{res}_{varname}/{res}_{varname}_{index}.npy" }



