varname: ???
res: ???
tset: ???
usf: ???
index: ???

dataset_root:  "/explore/nobackup/people/jli30/share/data/"
dataset_files: { lr: "${dataset.varname}_192x192/${.tset}/${.res}_${dataset.varname}/X${.usf}/${.res}_${dataset.varname}_${.index}.npy",
                 hr: "${dataset.varname}_192x192/${.tset}/${.res}_${dataset.varname}/${.res}_${dataset.varname}_${.index}.npy" }